# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: ruff-check
      name: ruff check
      entry: ruff
      language: system
      types: [python]
    - id: mypy
      name: type check
      entry: mypy
      language: system
      types: [python]
default_language_version:
  python: python3.10
files: ""
fail_fast: true