#!/usr/bin/env bash
# activate the virtualenv

if [ "$1" = 'production' ]; then
	DOTENV_FILE=".env.prod"
elif [ "$1" = 'development' ] || [ -z "$1" ]; then
	DOTENV_FILE=".env"
elif [ "$1" = 'testing' ]; then
	DOTENV_FILE=".env.test"
fi

ENV_PREFIX="$(pwd)/.venv"
if ! [ -d "$ENV_PREFIX" ]; then
	echo 'No virtualenv found. Use `make init` to create one.' >&2
	return 1
fi

# if the virtualenv is already activated
# ignore this script
if ! [ -z "$VIRTUAL_ENV" ]; then
	echo "Virtualenv $VIRTUAL_ENV already activated" >&2
	return
fi

export ENV_PREFIX
echo "Activating virtualenv $(basename $ENV_PREFIX)"

# activate virtualenv
source $ENV_PREFIX/bin/activate

# load env vars
# if the env file exists and is not empty
if [ -s "$DOTENV_FILE" ]; then
	echo "Loading environment variables from $DOTENV_FILE"
	export $(grep -v '^#' $DOTENV_FILE | xargs -d '\n')
fi
unset DOTENV_FILE