[default]
DEBUG = false
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
TITLE = "cookgpt"
SECRET_KEY = "Pl3453Ch4ng3"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "cookgpt.ext.config:init_app",
    "cookgpt.ext.database:init_app",
    "cookgpt.ext.auth:init_app",
    "cookgpt.ext.admin:init_app",
    "cookgpt.ext.commands:init_app",
    "cookgpt.ext.cors:init_app",
]
BLUEPRINTS = [
    "cookgpt.user:app",
    "cookgpt.auth:app",
]

JWT_TOKEN_LOCATION = ['headers', 'cookies']
JWT_HEADER_NAME = 'Authorization'
JWT_HEADER_TYPE = 'Bearer'
JWT_ACCESS_COOKIE_NAME = 'x_access_token'
JWT_REFRESH_COOKIE_NAME = 'x_refresh_token'
JWT_COOKIE_SAMESITE = 'Lax'
JWT_COOKIE_SECURE = false
JWT_COOKIE_CSRF_PROTECT = false


[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
JWT_ACCESS_TOKEN_EXPIRES = {days = 1}
JWT_ACCESS_TOKEN_LEEWAY = {hours = 12}


[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'
TESTING = true
DEBUG = true
JWT_ACCESS_TOKEN_EXPIRES = {minutes = 2}
JWT_ACCESS_TOKEN_LEEWAY = {minutes = 1}

[production]
JWT_ACCESS_TOKEN_EXPIRES = {days = 7}
JWT_ACCESS_TOKEN_LEEWAY = {days = 5}
JWT_COOKIE_SAMESITE = 'None'
JWT_COOKIE_SECURE = true
