[default]
DEBUG = false
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
TITLE = "cookgpt"
SECRET_KEY = "Pl3453Ch4ng3"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "cookgpt.ext.database:init_app",
    "cookgpt.ext.auth:init_app",
    "cookgpt.ext.admin:init_app",
    "cookgpt.ext.commands:init_app",
    "cookgpt.ext.cors:init_app",
]
BLUEPRINTS = [
    "cookgpt.user:app",
]

[development]
DEBUG = true


[testing]
TESTING = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'
