"""Initial Migration

Revision ID: f3d6087e900c
Revises:
Create Date: 2023-07-25 11:30:21.002145

"""
from datetime import datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

now = datetime.utcnow


# revision identifiers, used by Alembic.
revision = "f3d6087e900c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column("last_name", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=40), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=True),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False, primary_key=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=now),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            default=now,
            onupdate=now,
        ),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "jwt_token",
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False, default=False),
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), nullable=False, primary_key=True, default=uuid4
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=now),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            default=now,
            onupdate=now,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.UniqueConstraint("access_token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jwt_token")
    op.drop_table("user")
    # ### end Alembic commands ###
