name: Deploy To Heroku

permissions: write-all

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  deploy-doc:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: "6c3583c2-1448-4ff3-9c8c-eda314881628"
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.json
  api-diff:
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: ${{env.BUMP_DOC_ID}}
          token: ${{secrets.BUMP_TOKEN}}
          file: openapi.json
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "mkpbackend"
        heroku_email: "davemcsavvii@gmail.com"
        env_file: ".env.production"
  automerge:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
          MERGE_DELETE_BRANCH: false
          PULL_REQUEST: ${{ github.event.number }}
          PULL_REQUEST_BRANCH: ${{ github.event.pull_request.head.ref }}
