name: Deploy New Version

permissions: write-all

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "zingela-api"
        heroku_email: "davemcsavvii@gmail.com"
        env_file: ".env"
  automerge:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: Automerge pull request #${{ github.event.number }} into main
          MERGE_DELETE_BRANCH: false
          PULL_REQUEST: ${{ github.event.number }}
          PULL_REQUEST_BRANCH: ${{ github.event.pull_request.head.ref }}