# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: QA

on:
  pull_request:
    branches: [ dev ]

permissions: write-all


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install project
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Run linter
        run: make lint
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install project
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: |
          export FLASK_SECRET_KEY=testing
          export FLASK_SQLALCHEMY_DATABASE_URI=sqlite:///testing.db
          make test
  automerge:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
          MERGE_DELETE_BRANCH: true
          PULL_REQUEST: ${{ github.event.number }}
