# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: CI

on:
  pull_request:
    branches: [ dev ]

permissions:
  contents: read
  pull-requests: write


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
      - name: Install project
        run: |
          python -m pip install pipenv
          make install
      - name: Run linter
        run: make lint
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
      - name: Install project
        run: |
          python -m pip install pipenv
          make install
      - name: Run tests
        run: make test
  automerge:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: Automerge pull request #${{ github.event.number }} into dev
          MERGE_DELETE_BRANCH: true
          PULL_REQUEST: ${{ github.event.number }}