name: Release A New Version

permissions: write-all

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: [ '*.*.*' ]

jobs:
  release:
    name: Create New Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Generate Changelog
        run: .github/release_message.sh > release_message.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_message.md
  pull-request:
    name: Pr To Main
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Changelog
        run: .github/release_message.sh > pr_body.md
      - name: Create Pull Request
        run: |
          TAG=$(git tag -l | tail -1)
          TITLE="Bump version to $TAG"
          BODY=$(cat pr_body.md)
          gh pr create -B main -H dev -l automerge -b "$BODY" -t "$TITLE"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
